[package]
edition = "2018"
name = "one"
resolver = "1"
version = "0.1.0"

# [features]
# activate_hex = ["two/hex"]

[dependencies]
two = { path = "../two" }

[patch.crates-io]
hex = { path = "../hex_patch" }
